### ISSUE TITLE
Documentation of V5 protocol

### ISSUE THREAD

**Issue by stravinci** [serek4/node-red-sofar-ktl-x#1]
Hi,
My inverter is KTL-x 6.6 and after hello-msg sends msgs with length 116bytes, 146bytes, 14bytes or 268bytes.
Can you try to implement it?

here is some documentation of V5 protocol:
[Solarman Logger V5 Protocol Access to SDK.pdf](https://github.com/serek4/node-red-sofar-ktl-x/files/7474280/Solarman.Logger.V5.Protocol.Access.to.SDK.pdf)
[逆变器参数Inverter Parameters.xlsx](https://github.com/serek4/node-red-sofar-ktl-x/files/7474281/Inverter.Parameters.xlsx)
[Logger alarm code.xlsx](https://github.com/serek4/node-red-sofar-ktl-x/files/7474282/Logger.alarm.code.xlsx)

**Comment by serek4** [comment]
Sorry but i can't. I don't really know too much about logger protocol. Data is mostly decoded by capturing data from my logger and comparing with https://home.solarman.cn data.
