### ISSUE TITLE
Decode SOFAR HYD 15KTL-3PH

### ISSUE THREAD

**Issue by GusakIurii** [serek4/node-red-sofar-ktl-x#2]
Greetings.
Thanks for the info, you did a great job.
I tried to connect your block "node-red-sofar-ktl-x" to Wifi logger Firmware version LSW3_14_270A_1.08 inverter SOFAR HYD 15KTL-3PH, but my data does not match.
The inverter sends me two packets:

1. Length 14, every 2 minutes
Inverter : msg.payload : buffer[14]
[ 165, 1, 0, 16, 71, 31, 32, 6, 244, 70 … ]

2. Length 834, every 5 minutes

inverter : msg.payload : buffer[834]
[ 165, 53, 3, 16, 66, 32, 33, 6, 244, 70 … ]

I have a modbus table for this inverter, but I don’t know how to find the correspondence between addresses and actual data.
Can you send the address table from where you filled in the "decode msg" function?

**Comment by serek4** [comment]
I did not use any table, i logged data to file, than with [hex editor](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor) compared with https://home.solarman.cn/ data to find what is what. I took me some time but [here](https://github.com/serek4/node-red-sofar-ktl-x/tree/master/messages) are my results.

If u can get data from [this python script](https://github.com/MichaluxPL/Sofar_LSW3), i will have node-red implementation in the near future.
